object frmKeyboard: TfrmKeyboard
  Left = 0
  Top = 0
  BorderStyle = bsSizeToolWin
  Caption = 'Keyboard'
  ClientHeight = 286
  ClientWidth = 956
  Color = 16775920
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  FormStyle = fsStayOnTop
  OldCreateOrder = False
  Position = poOwnerFormCenter
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
end
