program AOPRSimReplay;

uses
  Forms,
  Dialogs,
  uTCPDatatype in '..\SimFramework\LibNets\NetComponent\uTCPDatatype.pas',
  tttData in '..\LibTTT\libDBScenario\tttData.pas',
  uGameData_TTT in '..\LibTTT\netTTT\uGameData_TTT.pas',
  uNetSessionData in '..\LibTTT\libNetSession\uNetSessionData.pas',
  uNetBaseSocket in '..\SimFramework\LibNets\NetComponent\uNetBaseSocket.pas',
  uPacketRegister in '..\SimFramework\LibNets\NetComponent\uPacketRegister.pas',
  uThreadTimer in '..\SimFramework\LibBaseUtils\Counter\uThreadTimer.pas',
  uLibSettingTTT in '..\LibTTT\uLibSettingTTT.pas',
  uCodecBase64 in '..\SimFramework\LibComponent\Base64\uCodecBase64.pas',
  uIniFilesProcs in '..\SimFramework\LibBaseUtils\uIniFilesProcs.pas',
  uVirtualTime in '..\SimFramework\LibBaseUtils\Counter\uVirtualTime.pas',
  newClassASTT in '..\LibTTT\libDBScenario\newClassASTT.pas',
  uDBAssetObject in '..\LibTTT\libDBScenario\uDBAssetObject.pas',
  uDBRainfall in '..\LibTTT\libDBScenario\uDBRainfall.pas',
  uDBScenario in '..\LibTTT\libDBScenario\uDBScenario.pas',
  uSimManager in '..\LibTTT\uSimManager.pas',
  uT3UnitContainer in '..\LibTTT\libUnit\uT3UnitContainer.pas',
  uBaseSimCenter in '..\SimFramework\LibSims\SimSystem\uBaseSimCenter.pas',
  uBaseSimObjects in '..\SimFramework\LibSims\SimSystem\uBaseSimObjects.pas',
  uSimContainers in '..\SimFramework\LibSims\SimSystem\uSimContainers.pas',
  uSimObjects in '..\SimFramework\LibSims\SimSystem\uSimObjects.pas',
  uDBGame_Defaults in '..\LibTTT\libDBScenario\uDBGame_Defaults.pas',
  uDataModuleTTT in '..\LibTTT\forms\uDataModuleTTT.pas' {dmTTT: TDataModule},
  uDBAsset_AccousticDecoy in '..\LibTTT\libDBScenario\uDBAsset_AccousticDecoy.pas',
  uDBAsset_Bomb in '..\LibTTT\libDBScenario\uDBAsset_Bomb.pas',
  uDBAsset_Chaff in '..\LibTTT\libDBScenario\uDBAsset_Chaff.pas',
  uDBAsset_ChaffLauncher in '..\LibTTT\libDBScenario\uDBAsset_ChaffLauncher.pas',
  uDBAsset_Countermeasure in '..\LibTTT\libDBScenario\uDBAsset_Countermeasure.pas',
  uDBAsset_Cubicle in '..\LibTTT\libDBScenario\uDBAsset_Cubicle.pas',
  uDBAsset_DefensiveJammer in '..\LibTTT\libDBScenario\uDBAsset_DefensiveJammer.pas',
  uDBAsset_Deploy in '..\LibTTT\libDBScenario\uDBAsset_Deploy.pas',
  uDBAsset_EO in '..\LibTTT\libDBScenario\uDBAsset_EO.pas',
  uDBAsset_ESM in '..\LibTTT\libDBScenario\uDBAsset_ESM.pas',
  uDBAsset_FCR in '..\LibTTT\libDBScenario\uDBAsset_FCR.pas',
  uDBAsset_Fitted in '..\LibTTT\libDBScenario\uDBAsset_Fitted.pas',
  uDBAsset_FittedWeapon in '..\LibTTT\libDBScenario\uDBAsset_FittedWeapon.pas',
  uDBAsset_FloatingDecoy in '..\LibTTT\libDBScenario\uDBAsset_FloatingDecoy.pas',
  uDBAsset_GameDefaults in '..\LibTTT\libDBScenario\uDBAsset_GameDefaults.pas',
  uDBAsset_GameEnvironment in '..\LibTTT\libDBScenario\uDBAsset_GameEnvironment.pas',
  uDBAsset_Geo in '..\LibTTT\libDBScenario\uDBAsset_Geo.pas',
  uDBAsset_Gun in '..\LibTTT\libDBScenario\uDBAsset_Gun.pas',
  uDBAsset_InfraredDecoy in '..\LibTTT\libDBScenario\uDBAsset_InfraredDecoy.pas',
  uDBAsset_MotionCharacteristics in '..\LibTTT\libDBScenario\uDBAsset_MotionCharacteristics.pas',
  uDBAsset_Radar in '..\LibTTT\libDBScenario\uDBAsset_Radar.pas',
  uDBAsset_Reference_Point in '..\LibTTT\libDBScenario\uDBAsset_Reference_Point.pas',
  uDBAsset_Runtime_Platform_Library in '..\LibTTT\libDBScenario\uDBAsset_Runtime_Platform_Library.pas',
  uDBAsset_Satellite in '..\LibTTT\libDBScenario\uDBAsset_Satellite.pas',
  uDBAsset_Scripted in '..\LibTTT\libDBScenario\uDBAsset_Scripted.pas',
  uDBAsset_Sensor in '..\LibTTT\libDBScenario\uDBAsset_Sensor.pas',
  uDBAsset_Sonar in '..\LibTTT\libDBScenario\uDBAsset_Sonar.pas',
  uDBAsset_Sonobuoy in '..\LibTTT\libDBScenario\uDBAsset_Sonobuoy.pas',
  uDBAsset_Vehicle in '..\LibTTT\libDBScenario\uDBAsset_Vehicle.pas',
  uDBAsset_Weapon in '..\LibTTT\libDBScenario\uDBAsset_Weapon.pas',
  uDBNote_Storage in '..\LibTTT\libDBScenario\uDBNote_Storage.pas',
  uDBBlind_Zone in '..\LibTTT\libDBScenario\uDBBlind_Zone.pas',
  uDBCloud_Effect in '..\LibTTT\libDBScenario\uDBCloud_Effect.pas',
  uDBCubicles in '..\LibTTT\libDBScenario\uDBCubicles.pas',
  uDBDefault_Var in '..\LibTTT\libDBScenario\uDBDefault_Var.pas',
  uT3SimManager in '..\LibTTT\uT3SimManager.pas',
  uDataTypes in '..\SimFramework\LibBaseUtils\CoordSystem\uDataTypes.pas',
  uObjectVisuals in '..\LibTTT\libVisual\uObjectVisuals.pas',
  uSimVisuals in '..\LibTTT\libVisual\uSimVisuals.pas',
  uCoordConvertor in '..\SimFramework\LibBaseUtils\CoordSystem\uCoordConvertor.pas',
  uBaseCoordSystem in '..\SimFramework\LibBaseUtils\CoordSystem\uBaseCoordSystem.pas',
  uStringFunc in '..\SimFramework\LibBaseUtils\StringUtils\uStringFunc.pas',
  uCalculationEnvi in '..\LibTTT\uCalculationEnvi.pas',
  uMapXHandler in '..\LibTTT\uMapXHandler.pas',
  uDBAssets_SubAreaEnviroDefinition in '..\LibTTT\libDBScenario\uDBAssets_SubAreaEnviroDefinition.pas',
  uDBFormation in '..\LibTTT\libDBScenario\uDBFormation.pas',
  uDBPattern in '..\LibTTT\libDBScenario\uDBPattern.pas',
  uDBLink in '..\LibTTT\libDBScenario\uDBLink.pas',
  ufProgress in '..\LibTTT\forms\ufProgress.pas' {frmProgress},
  uT3Unit in '..\LibTTT\libUnit\uT3Unit.pas',
  uT3Listener in '..\LibTTT\libUnit\uT3Listener.pas',
  uT3EventManager in '..\LibTTT\uT3EventManager.pas',
  uT3Torpedo in '..\LibTTT\libUnit\uT3Torpedo.pas',
  uT3Missile in '..\LibTTT\libUnit\uT3Missile.pas',
  uT3Vehicle in '..\LibTTT\libUnit\uT3Vehicle.pas',
  uT3Gun in '..\LibTTT\libUnit\uT3Gun.pas',
  uT3Common in '..\LibTTT\uT3Common.pas',
  uSteppers in '..\SimFramework\LibBaseUtils\Counter\uSteppers.pas',
  uT3DetectedTrack in '..\LibTTT\libUnit\uT3DetectedTrack.pas',
  uT3OtherSensor in '..\LibTTT\libUnit\uT3OtherSensor.pas',
  uT3Weapon in '..\LibTTT\libUnit\uT3Weapon.pas',
  uT3Bomb in '..\LibTTT\libUnit\uT3Bomb.pas',
  uT3CounterMeasure in '..\LibTTT\libUnit\uT3CounterMeasure.pas',
  uT3DataLink in '..\LibTTT\libUnit\uT3DataLink.pas',
  uT3Mine in '..\LibTTT\libUnit\uT3Mine.pas',
  uT3MissileDetail in '..\LibTTT\libUnit\uT3MissileDetail.pas',
  uT3MissileEnvironment in '..\LibTTT\libUnit\uT3MissileEnvironment.pas',
  uT3Radar in '..\LibTTT\libUnit\uT3Radar.pas',
  uT3Sensor in '..\LibTTT\libUnit\uT3Sensor.pas',
  uT3Sonar in '..\LibTTT\libUnit\uT3Sonar.pas',
  uT3SonarCD in '..\LibTTT\libUnit\uT3SonarCD.pas',
  u2DMover in '..\SimFramework\LibSims\SimsObjects\u2DMover.pas',
  uT3Visual in '..\LibTTT\libUnit\uT3Visual.pas',
  uGameSetting in '..\LibTTT\uGameSetting.pas',
  uScriptCommon in '..\LibTTT\uScriptCommon.pas',
  ufDBSetting in '..\LibTTT\forms\ufDBSetting.pas' {frmDBSetting},
  uMapXData in '..\LibTTT\uMapXData.pas',
  ufrmLog in 'ufrmLog.pas' {frmReplay},
  uCompassVisual in '..\LibTTT\libVisual\uCompassVisual.pas',
  uT3GroupList in '..\LibTTT\libNetSession\uT3GroupList.pas',
  GmXml in '..\SimFramework\LibComponent\XMLReader\GmXml.pas',
  GmXMLInterface in '..\SimFramework\LibComponent\XMLReader\GmXMLInterface.pas',
  uT3Sonobuoy in '..\LibTTT\libUnit\uT3Sonobuoy.pas',
  uT3HybridOnVehicle in '..\LibTTT\libUnit\uT3HybridOnVehicle.pas',
  uT3HybridMissile in '..\LibTTT\libUnit\uT3HybridMissile.pas',
  uT3DogBox in '..\LibTTT\libUnit\uT3DogBox.pas',
  uT3DefensiveJammer in '..\LibTTT\libUnit\uT3DefensiveJammer.pas',
  uT3RadarNoiseJammer in '..\LibTTT\libUnit\uT3RadarNoiseJammer.pas',
  uT3DatalinkManager in '..\LibTTT\libUnit\uT3DatalinkManager.pas',
  uTMapTouch2 in '..\LibTTT\uTMapTouch2.pas',
  uFilter in '..\LibTTT\libVisual\uFilter.pas',
  uFormationManager in '..\LibTTT\uFormationManager.pas',
  uDBAsset_Logistic in '..\LibTTT\libDBScenario\uDBAsset_Logistic.pas',
  uVectorVisual in '..\LibTTT\libVisual\uVectorVisual.pas',
  uRecord in '..\AOPRDBEditor.src\uRecord.pas',
  uCommonLogReplay in '..\AOPRReplay\uCommonLogReplay.pas',
  uGamePlayType in '..\AOPRReplay\uGamePlayType.pas',
  uNewReplay in '..\AOPRReplay\uNewReplay.pas',
  uRecorder in '..\AOPRReplay\uRecorder.pas',
  uSnapshotData in '..\AOPRReplay\uSnapshotData.pas',
  uSnapshotUtils in '..\AOPRReplay\uSnapshotUtils.pas',
  uSRRFunction in '..\AOPRReplay\uSRRFunction.pas',
  ufmMapWindow in '..\AOPRSimClient.src\formClient\frames\ufmMapWindow.pas' {fmMapWindow: TFrame},
  uReplayDataType in 'uReplayDataType.pas',
  uScriptSimReplay in 'uScriptSimReplay.pas',
  uT3ReplayClient in 'uT3ReplayClient.pas',
  uT3ReplayEventManager in 'uT3ReplayEventManager.pas',
  uT3ReplayManager in 'uT3ReplayManager.pas',
  ufMainDisplay in 'frmReplay\ufMainDisplay.pas' {frmMainDIsplay},
  uDBAsset_Embark_Library in '..\LibTTT\libDBScenario\uDBAsset_Embark_Library.pas',
  uEventSummary in '..\AOPRDBEditor.src\uEventSummary.pas',
  uDBAsset_FontTaktis in '..\LibTTT\libDBScenario\uDBAsset_FontTaktis.pas',
  uPlottingRecord in '..\AOPRDBEditor.src\uPlottingRecord.pas',
  uDBAsset_Capability in '..\LibTTT\libDBScenario\uDBAsset_Capability.pas',
  GdiPlus in '..\LibTTT\libGDIP\GdiPlus.pas',
  GDIPAPI in '..\LibTTT\libGDIP\GDIPAPI.pas',
  GDIPOBJ in '..\LibTTT\libGDIP\GDIPOBJ.pas',
  uFormula in '..\LibTTT\uFormula.pas',
  uBaseShape in '..\LibTTT\libObjects\uBaseShape.pas',
  uBrigadePersonel in '..\LibTTT\libObjects\uBrigadePersonel.pas',
  uDrawLogisticTemplate in '..\LibTTT\libObjects\uDrawLogisticTemplate.pas',
  uDrawOverlay in '..\LibTTT\libObjects\uDrawOverlay.pas',
  uDrawStrategi in '..\LibTTT\libObjects\uDrawStrategi.pas',
  uDynamicOverlay in '..\LibTTT\libObjects\uDynamicOverlay.pas',
  uMainDynamicShape in '..\LibTTT\libObjects\uMainDynamicShape.pas',
  uMainLogisticTemplate in '..\LibTTT\libObjects\uMainLogisticTemplate.pas',
  uMainOverlay in '..\LibTTT\libObjects\uMainOverlay.pas',
  uMainPlottingShape in '..\LibTTT\libObjects\uMainPlottingShape.pas',
  uMainStaticShape in '..\LibTTT\libObjects\uMainStaticShape.pas',
  uMainStrategi in '..\LibTTT\libObjects\uMainStrategi.pas',
  uWaypoint in '..\LibTTT\libObjects\uWaypoint.pas',
  uWeaponWaypoint in '..\LibTTT\libObjects\uWeaponWaypoint.pas',
  uT3GroupVehicle in '..\LibTTT\libUnit\uT3GroupVehicle.pas';

{$R *.res}


begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;

  Application.CreateForm(TdmTTT, dmTTT);
  Application.CreateForm(TfrmReplay, frmReplay);
  beginGameReplay;

  Application.CreateForm(TfrmMainDIsplay, frmMainDIsplay);
  Application.Run;

  EndGameReplay;
end.
